### ISSUE TITLE
initTrackScrollDepth exercises Firefox for Android bug causing crash

### ISSUE THREAD

**Issue by emdash-ie** [guardian/commercial#1388]
There is [a bug in Firefox for Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1853078) in which `window.innerHeight` is 0 in `window.onload` when a page is opened in a new tab. This was discovered in [a bug report about guardian pages causing Firefox for Android to crash](https://bugzilla.mozilla.org/show_bug.cgi?id=1788530), in which someone tracked the problem to the use of `window.innerHeight` [in initTrackScrollDepth](https://github.com/guardian/commercial/blob/901e31f9699c45cf093227c3632d29fedc03c2c5/src/core/track-scroll-depth.ts#L12).

Firefox for Android presumably will fix this bug, but in the meantime could we make a change here to avoid it (possibly just for firefox for android)? The current crashing behaviour is very frustrating to users (of which I am one), and we could possibly make a change more quickly than Firefox for Android will. Also, workarounds suggested for users in those bug threads are to click reject all on the consent banner or to use a uBlock Origin script to block the commercial bundle, so avoiding triggering the bug may avoid a reduction in the number of users who are shown consented ads.

**Comment by emdash-ie** [comment]
This is also the cause of https://github.com/guardian/dotcom-rendering/issues/6103

**Comment by mxdvl** [comment]
Specifically, a [division by `0` return `Infinity` in JS for the `pageHeightVH`](https://github.com/guardian/commercial/blob/901e31f9699c45cf093227c3632d29fedc03c2c5/src/core/track-scroll-depth.ts#L14)
